version: 2.1

orbs:
  node: circleci/node@2.1.1

executors:
  node-lts:
    docker:
      - image: cimg/node:lts

jobs:
  build-and-test:
    executor: node-lts
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - node/install
      - run: npm run test:unit
      - run: npm run test:integration

workflows:
    build-and-test:
      jobs:
        - build-and-test
